
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Compilador;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int CONT = 46;
  public static final int PARCER = 25;
  public static final int DOSPUNTOS = 23;
  public static final int POT = 11;
  public static final int CHARACD = 63;
  public static final int WRTE = 48;
  public static final int MULT = 10;
  public static final int CHAR = 38;
  public static final int SWT = 51;
  public static final int MENORQ = 16;
  public static final int GBAJO = 34;
  public static final int STRINGD = 66;
  public static final int ENTD = 60;
  public static final int CASE = 52;
  public static final int DOUBLE = 37;
  public static final int DECR = 6;
  public static final int INT = 36;
  public static final int MENORI = 17;
  public static final int INCR = 5;
  public static final int FOR = 53;
  public static final int LLCER = 27;
  public static final int NOT = 32;
  public static final int AND = 30;
  public static final int IGUAL = 14;
  public static final int DECD = 59;
  public static final int RTRN = 45;
  public static final int COMS = 35;
  public static final int LETRA = 3;
  public static final int OR = 31;
  public static final int BOOL = 39;
  public static final int PARAB = 24;
  public static final int DIV = 8;
  public static final int IF = 50;
  public static final int MAIN = 42;
  public static final int ID = 65;
  public static final int CORCER = 29;
  public static final int PYCOMA = 22;
  public static final int EOF = 0;
  public static final int LLAB = 26;
  public static final int ASIG = 13;
  public static final int TRUE = 57;
  public static final int NEW = 56;
  public static final int error = 1;
  public static final int DESIG = 15;
  public static final int COMA = 21;
  public static final int DIG = 2;
  public static final int CNSL = 47;
  public static final int MOD = 12;
  public static final int BOOLEAD = 64;
  public static final int VOID = 41;
  public static final int WhiteSpace = 4;
  public static final int CORAB = 28;
  public static final int ELSE = 49;
  public static final int PUNTO = 20;
  public static final int MAYORQ = 18;
  public static final int MEN = 9;
  public static final int WHILE = 54;
  public static final int BRK = 44;
  public static final int MAYORI = 19;
  public static final int COMENTS = 62;
  public static final int STRING = 40;
  public static final int DEF = 43;
  public static final int TER = 33;
  public static final int FALSE = 58;
  public static final int COMENTM = 61;
  public static final int DO = 55;
  public static final int MAS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DIG",
  "LETRA",
  "WhiteSpace",
  "INCR",
  "DECR",
  "MAS",
  "DIV",
  "MEN",
  "MULT",
  "POT",
  "MOD",
  "ASIG",
  "IGUAL",
  "DESIG",
  "MENORQ",
  "MENORI",
  "MAYORQ",
  "MAYORI",
  "PUNTO",
  "COMA",
  "PYCOMA",
  "DOSPUNTOS",
  "PARAB",
  "PARCER",
  "LLAB",
  "LLCER",
  "CORAB",
  "CORCER",
  "AND",
  "OR",
  "NOT",
  "TER",
  "GBAJO",
  "COMS",
  "INT",
  "DOUBLE",
  "CHAR",
  "BOOL",
  "STRING",
  "VOID",
  "MAIN",
  "DEF",
  "BRK",
  "RTRN",
  "CONT",
  "CNSL",
  "WRTE",
  "ELSE",
  "IF",
  "SWT",
  "CASE",
  "FOR",
  "WHILE",
  "DO",
  "NEW",
  "TRUE",
  "FALSE",
  "DECD",
  "ENTD",
  "COMENTM",
  "COMENTS",
  "CHARACD",
  "BOOLEAD",
  "ID",
  "STRINGD"
  };
}

